In [1]:
from numpy import *

In [2]:
a=array([2,3,4]) # создание одномерного массива из списка целых чисел

In [3]:
print(a)
a


[2 3 4]


array([2, 3, 4])

In [4]:
a.ndim # размерность массива (одномерный, двумерный и т.д.)

1

In [5]:
a.shape # размеры массива (число строк, столбцов и т.д.)

(3,)

In [6]:
b=array([(1.5, 2, 3), (4, 5, 6)]) # создание двумерного массива из двух последовательных чисел

In [7]:
print(b) # все числа имеют один тип - число с плавающей точкой

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [8]:
b.ndim

2

In [9]:
b.shape

(2, 3)

In [10]:
b.size

6

In [12]:
z=zeros((3, 2)) # 3 ,2 помещаются в дополнительный скобки, чтобы представлять из себя один объект-пару чисел

In [13]:
z

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
arange(10, 30, 5) # функция arange аналогична функции range, но возвращает массив

array([10, 15, 20, 25])

In [15]:
linspace(0, 2, 9) # генерирует 9 чисел на отрезке от 0 до 2 с равным шагом

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
b=arange(12).reshape(4, 3)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [19]:
a=array([10, 20, 30])
b=arange(3)
print(a)
print(b)

[10 20 30]
[0 1 2]


In [20]:
print(a+b) # арифметические операции на массивах выполняются поэлементно
print(a-b)

[10 21 32]
[10 19 28]


In [21]:
print(a**2)

[100 400 900]


In [22]:
2*sin(a)

array([-1.08804222,  1.8258905 , -1.97606325])

In [23]:
a<20

array([ True, False, False])