In [1]:
from numpy import *

In [2]:
a=array([2,3,4])
print(a)

[2 3 4]


In [3]:
a

array([2, 3, 4])

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [6]:
d=array([(1.5, 2.5, 3), (4, 5.2, 6.1)])
d.size

6

In [8]:
z=zeros((4, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
linspace(0, 50, 9)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  , 31.25, 37.5 , 43.75, 50.  ])

In [23]:
m=arange(12)
print(m)
m=arange(12).reshape(4, 3)
print(m)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [28]:
x=array([10, 15, 33, 46])
y=array([0, 8, 25, 74])
z=x+y
g=x-y
l=cos(x)*2
print(z)
print(g)
print(l)

[ 10  23  58 120]
[ 10   7   8 -28]
[-1.67814306 -1.51937583 -0.02655349 -0.86435589]


In [30]:
x<30

array([ True,  True, False, False])